### ISSUE TITLE
CommonTest.testToBitTypeImgPlus throws NullPointerException

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/BoneJ2#100]
The test throws a `NullPointerException` [here](https://github.com/bonej-org/BoneJ2/blob/master/Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/wrapperUtils/CommonTest.java#L60). Ultimately the cause is that the field `ij1Helper` in `net.imagej.legacy.LegacyService` is `null`. However, the exception only happens if the test is run from Maven! When I run the test in IntelliJ, it passes.

Steps to reproduce
* Depend on `pom-scijava:21.0.0` or newer
  - Specifically, he problem appears at `scijava-common:2.70.0`
* Depend on `imagej-legacy` (run time)
  - The issue doesn't appear if you don't have this dependency
* Remove the `@Ignore` annotation from the aforementioned test if necessary
* Run `mvn test`

**Comment by rimadoma** [comment]
The issue has been reproduced in two environments with different versions of Maven and JVM. On my computer they are `3.3.9` and `1.8.0_172` respectively.

 I was able to find the exact line by running `mvn -Dmaven.surefire.debug test` and then attaching the IntelliJ debugger to the process. Instructions for remote debugging [here](https://stackoverflow.com/questions/21114066/attach-intellij-idea-debugger-to-a-running-java-process) (port: _5005_).

**Comment by rimadoma** [comment]
Spoke too soon, issue still persisted (hence the [broken build](https://travis-ci.org/bonej-org/BoneJ2/builds/425762482)). I thought the problem had solved itself, because a Maven build succeeded  on my local machine, when I ran `mvn -PallTests test`. Thus I decided to add `@Category(org.bonej.wrapperPlugins.SlowWrapperTest.class)` to `CommonTest.testToBitTypeImgPlus`. This way we don't have to ignore the problematic test all together.

As far as I can see, the test shouldn't need this annotation. I don't yet understand why it succeeds only when ran together with the `SlowWrapperTests`.

**Comment by alessandrofelder** [comment]
@rimadoma I have had the same issue in [some ElllipsoidFactorWrapper tests](https://github.com/bonej-org/BoneJ2/blob/58a29254c09c3a5c9e56ba178c373a8e7911884b/Modern/wrapperPlugins/src/test/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapperTest.java#L73)

**Comment by rimadoma** [comment]
@alessandrofelder See if you can remove the annotations now too
