### ISSUE TITLE
Connectivity warns that "Calibration cannot be determined"

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#107]
This warning is shown to the user when correct data is provided: 3D binary (0 and 255) 8-bit image.

Spatial calibration is irrelevant for connectivity because it's a topological measure - this check and warning is unnecessary.

**Comment by rimadoma** [comment]
The warning relates to the connectivity density measure, which when displayed, needs a unit of volume. Since this is not the main result of interest for all, I can remove the warning. What do you think?

**Comment by mdoube** [comment]
In the case where there is no spatial calibration, connectivity should be reported in units of pixel ^-3.

-------- Original Message --------
