### ISSUE TITLE
Particle Analyser produces negative Enclosed Volume

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#112]
Enclosed volume is the volume calculated from the surface mesh.

In BoneJ2 the legacy particle analyser code reports negative enclosed volume. (Fiji with BoneJ installed from the update site)

Steps to reproduce:
Open bat cochlea sample image
Run Plugins > BoneJ > Analyze > Particle Analyser with the default settings

Perhaps the surface mesh is produced inside out.

This is the code that does the enclosed volume calculation:
```java
private static double[] getSurfaceVolume(
		final Collection<List<Point3f>> surfacePoints)
	{
		return surfacePoints.stream().mapToDouble(p -> {
			if (p == null) {
				return 0;
			}
			final CustomTriangleMesh mesh = new CustomTriangleMesh(p);
			return mesh.getVolume();
		}).toArray();
	}
```

**Comment by rimadoma** [comment]
I noticed I had left out the `Math.abs()` call when modifying code that originated from (here)[https://github.com/bonej-org/bonej/blob/master/src/org/doube/bonej/ParticleCounter.java#L958]. Calling `CustomTriangleMesh.getVolume()` returns the result of [this method](https://github.com/fiji/3D_Viewer/blob/master/src/main/java/isosurface/MeshProperties.java#L44). It might be worth creating an issue about negative mass in `sc.fiji.3D_Viewer`.

**Comment by mdoube** [comment]
Ah, so it is *my* hack! Touché.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
