### ISSUE TITLE
Result inserter puts data on first empty row when it should be on new row

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#117]
When a BoneJ2 trabecular analysis plugin completes, it should add its results to the first line with a Label that matches the image title, unless a new column has just been created, in which case all the data should go on the same new row and all the preceding empty rows should be left empty or a placeholder value e.g. NaN entered.

Steps to reproduce (Fiji with BoneJ cuneiform-experimental)
Unzip & Open [binary_noise.tif.zip](https://github.com/bonej-org/BoneJ2/files/2277003/binary_noise.tif.zip)
Run Plugins > BoneJ > Anisotropy (Directions 20, Lines 100, Sampling 1) show radii unchecked
Run Plugins > BoneJ > Anisotropy (Directions 20, Lines 100, Sampling 1) show radii checked

Expected behaviour: on second run, the radii should be added to the second row of the results table
Current behaviour: radii are added to the first row of the results table.

**Comment by mdoube** [comment]
This bug also affects BoneJ1

**Comment by mdoube** [comment]
Fixed for BoneJ1 and Legacy by https://github.com/mdoube/BoneJ/commit/ad0e42929b07004a43b2e75fd38fd7fd860c3944 and https://github.com/mdoube/BoneJ2/commit/80a9515be7d8e81ecda3b3f14882950bcf71071c

**Comment by rimadoma** [comment]
Could you create a pull request about the fix to `Legacy` please? Should the tests be updated so that there's one that succeeds when behaviour is as fixed, and fails when it's like the old behaviour?

**Comment by rimadoma** [comment]
Could you also check the documentation of [SharedTable](https://github.com/bonej-org/BoneJ2/wiki/Shared-table), and see that rules are what you had in mind, please? Also, please add a commit that updates the Javadoc of the class in your PR.

**Comment by mdoube** [comment]
Fixed by
https://github.com/mdoube/BoneJ2/commit/6617ad062d1d0918ec2ff32e301a0fc3ea0202d7
https://github.com/mdoube/BoneJ2/commit/9de0913b3257671b6efdca62906cdad39dcfeeaa

**Comment by rimadoma** [comment]
IMO an issue shouldn't be closed, until the commits that fix it have been merged to `master`

**Comment by mdoube** [comment]
OK - all protocol tips welcome.

**Comment by rimadoma** [comment]
Fixed in #126
