### ISSUE TITLE
Anisotropic pixel spacing check is too stringent

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#122]
**Describe the bug**
Some plugins assume isotropic pixel spacing (Anisotropy, Local Thickness), so there is a check to make sure pixels are not spaced anisotropically. The check is too stringent, so that if the pixel spacing values are not precisely the same, the warning is shown.

**To Reproduce**
Unzip and open the attached image
[binary_trabeculae_small.tif.zip](https://github.com/bonej-org/BoneJ2/files/2287187/binary_trabeculae_small.tif.zip)
Run Plugins > BoneJ > Anisotropy

**Expected behavior**
Anisotropy should complain only if pixel spacing is anisotropic outside a certain threshold (e.g. 0.01 or 0.001).

This method in AnisotropyWrapper is the problem:
```java
private boolean isCalibrationIsotropic() {
		final Optional<String> commonUnit = getSpatialUnit(inputImage, unitService);
		if (!commonUnit.isPresent()) {
			return false;
		}
		final String unit = commonUnit.get();
		return spatialAxisStream(inputImage).map(axis -> unitService.value(axis
			.averageScale(0, 1), axis.unit(), unit)).distinct().count() == 1;
	}
```

**Comment by rimadoma** [comment]
* Make method into a `public static` utility method
* Add `final double tolerance` parameter
* Add tests
  - Isotropic calibration returns true
  - Anisotropic calibration within tolerance returns true
  - Anisotropic calibration larger than tolerance returns false
  - Negative tolerance throws `IllegalArgumentException`
  - No common unit returns false
  - Inconvertible units returns false (?)

**Comment by mdoube** [comment]
I note that there is another method which looks like it might do anisotropy checking in [wrapperUtils.Common](
https://github.com/bonej-org/BoneJ2/blob/master/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java#L73)

**Comment by rimadoma** [comment]
That method is for `ImagePlus`, whereas the method created in #127 is for `ImgPlus` (or any `Space` that has `CalibratedAxis`). I'll make sure they have the same tolerance
