### ISSUE TITLE
SharedTable uses String for numerical data storage

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#125]
SharedTable uses String for numerical data storage.

This is inefficient because a char is stored for every numeral in the value. It might not scale very well for tables containing a lot of data.

It may be a compromise position because image titles are Strings, and it might not be allowed to have one column of String and the rest Double in the table. On the other hand it is possible to set a String row header, but that has to be unique, so multiple rows using the same image title would have to be disambiguated with e.g. a suffix like ImageTitle, ImageTitle.1, ImageTitle.2 and so on.

Alternatively, could it be possible to declare the Table to contain data of type Object so that cells could contain String or Double without restriction?

**Comment by mdoube** [comment]
It is allowed to have repeated rowHeaders, now used in https://github.com/mdoube/BoneJ2/commit/6617ad062d1d0918ec2ff32e301a0fc3ea0202d7

**Comment by mdoube** [comment]
shared table now stores numerical values as Doubles, and empty cells as null
https://github.com/mdoube/BoneJ2/commit/16857241625d571a691fd964631ca299e236891b

**Comment by ctrueden** [comment]
Why are you using `DefaultColumn<Double>`? Why not `DoubleColumn`? It is far more space efficient, backed by a `double[]` instead of a `List` of boxed `Double` objects.

**Comment by mdoube** [comment]
@ctrueden good point, will rectify for the next release of the table

**Comment by rimadoma** [comment]
@ctrueden @mdoube The reason we're using `Double` instead of `double[]` is that (correct me if I'm wrong) with the former we can have `null` cells in the table. They denote special empty cells, which don't have values yet. Using `NaN` or `0` is problematic, because sometimes you might actually get those values as results, and then you can't tell between results and empty cells.

**Comment by mdoube** [comment]
@rimadoma raises an important point. Swapping in DoubleColumn breaks lots of tests, perhaps for this reason. Reverted to DefaultColumn<Double>.
