### ISSUE TITLE
Can't easily save BoneJ results from table

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#129]
BoneJ2 results are stored in a SharedTable called "BoneJ results" and displayed to the user (or not, if running headless).

There appears to be no programmatic way to save the results - commands from the File menu have no effect, and there is no 'save' method in the parent Table class.

It is possible to copy paste via the UI into a spreadsheet like LibreOffice Calc or into a text editor.

Users need a way to save table data via UI and scripts.

**Comment by imagejan** [comment]
FYI, the `net.imagej.table.*` classes will soon be deprecated and replaced by `org.scijava.table.*` from [`scijava-table`](https://github.com/scijava/scijava-table). Except for the package naming and dependencies, the API is mostly unchanged. See https://github.com/imagej/imagej-common/pull/78 for details.

Together with this move, we also moved the IO component to [`scijava-plugins-io-table`](https://github.com/scijava/scijava-plugins-io-table), see also https://github.com/scijava/scijava-plugins-io-table/pull/3.

There are plans to integrate some UI in the table display to allow saving of tables: https://github.com/imagej/imagej-common/issues/75

If you're missing any functionality, or consider some parts of `SharedTable` etc. worth being moved into the respective SciJava component, I'd be happy to know and accept PRs :)

**Comment by tristan05** [comment]
Hello -

I am using boneJ2 via the ImageJ-Matlab interface. I would like to get numerical results from the "BoneJ results" table back to Matlab, but it does not appear as though the results window is treated as a table in Fiji. Is there a programmatic workaround to automatically store numerical results? 
By the way, copy and paste of the results does not work when boneJ2 is being run via Matlab.
Many thanks,
Tristan

**Comment by mdoube** [comment]
@tristan05 please make a forum post requesting assistance with this https://forum.image.sc/

**Comment by mdoube** [comment]
There is a workaround mentioned here to export tables:
https://forum.image.sc/t/accessing-bonej2-results-table-via-imagej-matlab/29252/5
Need to get the snapshots finished off and included in the user release.

**Comment by imagejan** [comment]
All components are released and pinned in the latest `pom-scijava`.

[`<scijava-plugins-io-table.version>0.2.0</scijava-plugins-io-table.version>`](
https://github.com/scijava/pom-scijava/blob/91b83b6c1a24cbedfef847d87d6eb85ce2387d1b/pom.xml#L279-L280)

[`<scijava-table.version>0.5.0</scijava-table.version>`](https://github.com/scijava/pom-scijava/blob/91b83b6c1a24cbedfef847d87d6eb85ce2387d1b/pom.xml#L294-L295)

No need to pin to any `SNAPSHOT` versions. With the next big round of Fiji updates (by @ctrueden) these will be available from the Java-8 update site.

**Comment by mdoube** [comment]
This is now fixed by the user command  _File > Export > Table ... _
