### ISSUE TITLE
Thickness produces extra rows in the result table

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#132]
**Describe the bug**
When Thickness completes, it adds two new rows to the result table:
ImageTitle_Tb.Th
Image Title_Tb.Sp

**To Reproduce**
1. Open an image
2. Run Plugins > BoneJ > Thickness

**Expected behavior**
Results should be entered in the row with label according to the original input image

**Screenshots**
![screenshot from 2018-09-04 09-31-51](https://user-images.githubusercontent.com/87103/45005367-7bacc980-b025-11e8-955e-a37663687a9a.png)

**Environment**
 - OS: Ubuntu 16.04
 - Java version: 1.8.0_172 (Oracle)
 - Fiji updated today
- BoneJ2 5e3be0cd69b833fa06a71be3a85532ab597b8441

**Comment by rimadoma** [comment]
My reasoning was that since the thickness map images have different titles than the original, it would make sense for them to have separate rows. I can appreciate why you'd prefer the results on one row.

**Comment by mdoube** [comment]
The point of the result inserter / shared table is that you get all the data about a particular sample (image) on the same row, which is convenient for later analysis. Should be an easy fix?

**Comment by rimadoma** [comment]
Yes, you just need to change the labels inserted to the table in `ThicknessWrapper` (also the tests of the plug-in will need an update).
