### ISSUE TITLE
Quick Search Help Button resolves to empty Wiki page

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#145]
Running the Quick Search gives some info about plugins, including a Help button, which resolves to https://imagej.net/<Plugin_Menu_Text> by default

All of BonejJ2's user docs are at https://imagej.net/BoneJ2, so we need to make redirects on the Wiki to where the actual user docs are.

Then the Quick Search Help Button will resolve to user documentation

**Comment by mdoube** [comment]
@ctrueden is there an easy way to do this - e.g. by making stubs on the Wiki that just redirect, like when you move a page, or rename a person?

**Comment by mdoube** [comment]
There is an easy way to do this. For each command, you need to edit the automatically generated wiki page with a `#REDIRECT` statement, e.g. for the Connectivity menu item, which by default resolves to `https://imagej.net/Connectivity`, the Wiki markup looks like:

```#REDIRECT [[BoneJ2#Connectivity]]```

**Comment by ctrueden** [comment]
You got it, @mdoube. Glad you figured it out! I agree that redirects to the appropriate anchors are the way to go here.

**Comment by mdoube** [comment]
Made redirects from all menu commands except:

- Particle Analyser, which is missing from imagej.net/BoneJ2
- Ellipsoid Factor, which can have its links made during @alessandrofelder's Navicular release
- Optimise Threshold, which is a candidate for deprecation & removal

**Comment by mdoube** [comment]
> The eventual idea would be to add a `url` field to the `@Plugin` annotation,

OK, good. The redirect approach is problematic, and a hack that works for now. If an implementation arises then the help button should do something like, check to see if there is a URL in the plugin's annotation and follow it, otherwise go to the Wiki. That will make migration seamless to users and robust across plugin versions. I didn't test whether the Wiki allows redirects to domains outside imagej.net (e.g. to bonej.org, which we might use to serve modern resources in the future).
