### ISSUE TITLE
Binary images not recognised by input checking

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#150]
**Describe the bug**
The result of Image > Adjust > Threshold > Apply is not recognised by BoneJ / Fraction / Area Fraction as being binary, despite being binary (0,255).

**To Reproduce**
1.  Open a greyscale image
2.  Run Image > Adjust > Threshold > Apply
3.  Run Plugins > BoneJ > Fraction > Area/volume Fraction

**Expected behavior**
The plugin runs and gives a result

**Additional context**
Input checking appears not to recognise the result of Image > Adjust > Threshold as binary. Duplicating a slice or subvolume of the non-working binary image with Shift +D results in an image that is recognised as binary.

**Comment by mdoube** [comment]
My guess is that there is a problem with the way [this method](https://github.com/bonej-org/BoneJ2/blob/master/Modern/utilities/src/main/java/org/bonej/utilities/ElementUtil.java#L108) handles legacy ImagePlus pixel data.

**Comment by mdoube** [comment]
@ctrueden is there a better way to detect whether an image is binary, which works for modern and legacy images?

**Comment by mdoube** [comment]
@ctrueden is there a better way to detect whether an image is binary, which works for modern and legacy images?

**Comment by mdoube** [comment]
Cannot replicate with an up to date Fiji, closing.

**Comment by ctrueden** [comment]
@mdoube Sorry for dropping the ball on responding to this, and glad to hear it is working now.
