### ISSUE TITLE
Build scripts fail with DependencyResolutionException

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#156]
**Describe the bug**
The build scripts `IJinstall.sh` and `IJinstall_naughty.sh` fail with the following error:

```[ERROR] Failed to execute goal net.imagej:imagej-maven-plugin:0.7.0:copy-jars (copy-jars) on project pom-bonej: Couldn't resolve dependencies for artifact: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.bonej:pom-bonej:jar:6.0.1-SNAPSHOT in imagej.public (https://maven.imagej.net/content/groups/public) -> [Help 1]```

This is despite all tests passing and `mvn clean install` passing and copying newly-compiled artefacts to the local repository.

**To Reproduce**
1. On the command line go to the git repository for bonej-aggregator
2. run `./IJinstall_naughty.sh <path/to/your/Fiji.app>`

**Expected behavior**
BoneJ compiles and jars are copied into Fiji.app/plugins; old BoneJ jars are deleted from Fiji.app/plugins

**Additional Context**
The build scripts do this:
`mvn -Dimagej.app.directory="$1" -Ddelete.other.versions=true -Dmaven.test.skip=true clean install
`

**Comment by rimadoma** [comment]
This is a known issue with imagej-maven-plugin:0.7.0. That's why I set pom to use 0.6.0. Has that been removed? 

Issue is fixed in 0.7.1, but I don't know if it's out yet.

**Comment by mdoube** [comment]
Thanks @rimadoma. Where do we set which version of imagej-maven-plugin to use?

**Comment by rimadoma** [comment]
@mdoube it was on pom.xml at root of Modern before I left. It goes in <configuration>

**Comment by mdoube** [comment]
> It goes in
...?

**Comment by mdoube** [comment]
This commit 41b6fd2 by @ctrueden removed the `pom.xml` files from Modern and Legacy and thus the version @rimadoma set for `imagej-maven-plugin`.

Looks like this `<build>` block needs to be put back - where would be a good place to do that?

**Comment by mdoube** [comment]
Leaving this issue open for now because the install scripts still contain deprecated code and the top-level `pom.xml` has the version downgrade in it.

**Comment by ctrueden** [comment]
I changed it to the newest version of imagej-maven-plugin (https://github.com/bonej-org/BoneJ2/commit/621afe10013f324ad169553c5ffe3722d355315b) and the Travis build [passed this time](https://travis-ci.org/bonej-org/BoneJ2/builds/457659873). Personally I think it is fine to close this issue. The switch to scijava-maven-plugin will happen automatically with the commit that updates the pom-scijava parent version in the future.

**Comment by mdoube** [comment]
Confirming, build works here with imagej-maven-plugin 0.7.1
