### ISSUE TITLE
Anisotropy calculated from radii not eigenvalues

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#180]
**Describe the bug**
Anisotropy should be calculated as DA = 1 - minEigenValue / maxEigenValue, but it is calculated using radii: 

https://github.com/bonej-org/BoneJ2/blob/5b7c4af588b8a344dd82bf176b17bf796d1a6b9a/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/AnisotropyWrapper.java#L127

**Comment by rimadoma** [comment]
The radii are directly derived from the eigenvalues so their ratio is the same

**Comment by mdoube** [comment]
> The radii are directly derived from the eigenvalues so their ratio is the same

No it is not because the radius:eigenvalue relation is an inverse square, so the big radius has the small eigenvalue and vice versa.

let's say r = 2 and R = 5, DA would be 1 - 2/5 = 0.6

v = 1/r² for a 3×3 ellipsoid tensor

then V = 1/2² = 0.25 and v = 1/5² = 0.04 and DA = 1 - 0.04/0.25 = 0.16

**Comment by mdoube** [comment]
Fixed by #181 and #187
