### ISSUE TITLE
Anisotropy does not recognize image stack as 3D image

### ISSUE THREAD

**Issue by SebastienCallens** [bonej-org/BoneJ2#248]
Hello, I have an issue with some of the tools in BoneJ2, including the anisotropy tool. Whenever I try to run it on a stack of binarized images (see attached file), I get the error message that a "3D image" is required. This also happens when I try the anisotropy tool on the EF test images. 

Do you know how I should convert the image stack into a suitable 3D image for the anistropy calculation? I don't understand why it is not accepted in its current format. 

Thanks a lot in advance!

[testAnisotropy.zip](https://github.com/bonej-org/BoneJ2/files/4622338/testAnisotropy.zip)

**Comment by alessandrofelder** [comment]
Hello,
Thanks for getting in touch!
The issue with the test image you have provided is that the third dimension is temporal, not spatial.
You can change this in ImageJ via `Image>Properties`.
Can I ask you to post future questions on the [ImageJ forum](https://forum.image.sc/) with a BoneJ tag, so that they will be easier to find in the future, please?

Hope this helps!

@mdoube @rimadoma we might want to specify the fact that we expect 3 _spatial_ dimensions in error message? Just a thought...

**Comment by rimadoma** [comment]
> we expect 3 _spatial_ dimensions in the error message?

Not a bad idea. Do you have time to look at the EF test images?

**Comment by alessandrofelder** [comment]
I am not sure which EF test images @SebastienCallens refers too?
Just tested that Anisotropy works on `shrew.tif` now, which is an EF test image givee on [bonej.org](http://bonej.org/ef), and it does :)

**Comment by rimadoma** [comment]
> I am not sure which EF test images @SebastienCallens refers too?

I think images from _Plugins>BoneJ>Test images>Create EF test images_

**Comment by alessandrofelder** [comment]
Ooo yes, that is a 🐛 ! Thanks for spotting that, @SebastienCallens and @rimadoma !

Slightly different to @SebastienCallens problem because that command creates extra channel dimensions (which used to be OK for EF), not extra temporal dimensions, instead of z spatial dimensions. Will fix now.

**Comment by SebastienCallens** [comment]
Thanks a lot for getting back so quickly and for clarifying this issue! Regarding the EF images, I was indeed referring to the ones that @rimadoma mentioned. Just so you know, I could run my file without problems in BoneJ1. 

I will also make sure to post future questions in the forum. Thanks again!
