### ISSUE TITLE
Improved Installing BoneJ screenshot for wiki

### ISSUE THREAD

**Issue by rgaiacs** [bonej-org/BoneJ2#277]
I want to contribute the following image to https://github.com/bonej-org/BoneJ2/wiki/Installing-BoneJ

![install](https://user-images.githubusercontent.com/1506457/99342702-6dc28680-28c7-11eb-8524-409af1b6d519.png)

**Comment by mdoube** [comment]
Uploaded to https://github.com/imagej/imagej.github.io
