### ISSUE TITLE
Run tests in Travis

### ISSUE THREAD

**Issue by rgaiacs** [bonej-org/BoneJ2#284]
Can we use [Travis CI](https://www.travis-ci.com/) to run `mvn test -P allTests`? https://github.com/bonej-org/BoneJ2/pull/283 illustrates that we are **not** using Travis CI to run the tests.

**Comment by alessandrofelder** [comment]
Think the idea is that we don't run the "slow" (annotated with `@Category(org.bonej.wrapperPlugins.SlowWrapperTest.class`) tests on Travis - as they tend to time out from time to time, indicating a bug when there is none. It's documented in [the wiki (pt 5.)](https://github.com/bonej-org/BoneJ2/wiki/Releasing-BoneJ) to check locally with `-P allTests` when we release the code... although probably good to do this more often than that.

I agree that the current situation is far from ideal wrt these issues. It _might_ be resolved by switching to GitHub actions (who offer machines with better specs and longer time-out limits (although I wouldn't count on this - we should consider this if the whole of ImageJ switches to GitHub actions, which is a possibility [apparently](https://forum.image.sc/t/which-imagej-related-tasks-would-help-you-the-most/48041)). So maybe it's worth experimenting with? I don't know

**Comment by mdoube** [comment]
I wonder if this has something to do with #300 ?

**Comment by alessandrofelder** [comment]
In what way do you mean, @mdoube ? Are you suggesting that all wrapperPlugins annotated with `@Category(org.bonej.wrapperPlugins.SlowWrapperTest.class)` suffer from the same zombie thread business, and are too slow to not time out on Travis for this reason?

**Comment by mdoube** [comment]
More like the zombies slow everything down and cause the whole job to time out. Zombie threads / bad threading model might also be behind the recurring test failure we get with Fractal Dimension #229

**Comment by mdoube** [comment]
Closing, testing and CI has moved to Github Actions
