### ISSUE TITLE
Anisotropy, Is there a way to output a table of MIL vectors rather then the point cloud? 

### ISSUE THREAD

**Issue by harshamarupudi56** [bonej-org/BoneJ2#319]
I'd like to output the values generated by the point cloud vector as a table. Would be helpful for a user to be able to save it a different format if they wish rather then the 3D point cloud. Looking at the Java source code for the Anisotropy plugin I don't see an easy way to grab the calculation in Jython.

**Comment by mdoube** [comment]
Closed by #328
