### ISSUE TITLE
Null image shows wrong error message

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/BoneJ2#59]
When you try to run the plugins with no images open, the user sees the wrong error message:  _"A ImgPlus is required but none exist"_. They should see a clearer _"No image open"_ message. 

The plugins check for null in the "validater" (sic) method of their image parameters. At least with the legacy UI execution of a plugin doesn't get this far before it's stopped with the wrong message. However, the tests for proper cancel messages still pass. Thus the issue probably originates from some kind of automatic conversion going on with the legacy UI. This can be fixed by checking for `null` in the initializer of a @Parameter. The validater should then check for other properties of the image

**Comment by imagejan** [comment]
Maybe this is something worth to improve on the SciJava side? The error message is generated during input harvesting here:
https://github.com/scijava/scijava-common/blob/608831075023f9ddf053691a82c2be24458f337c/src/main/java/org/scijava/widget/AbstractInputHarvester.java#L122-L123

**Comment by rimadoma** [comment]
Could it be something as simple as 
```java
if (ImgPlus.class.isAssignableFrom(type) || Img.class.isAssignableFrom(type)) {
    throw new ModuleException("No image open");
}
```
?

**Comment by imagejan** [comment]
The message "No image open" doesn't make much sense if you run the command headless via scripting or from within KNIME.

**Comment by rimadoma** [comment]
Would _"The command requires an image"_ make more sense?

**Comment by rimadoma** [comment]
[PR created](https://github.com/scijava/scijava-common/pull/266)

**Comment by rimadoma** [comment]
PR rejected
