### ISSUE TITLE
Adopt ImageJ Eclipse code style profile

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/BoneJ2#7]
Adopt the ImageJ project's [code style profile](https://github.com/imagej/imagej/blob/master/config/eclipse-preferences.epf) to follow the "official" code formatting. 

Have to solve the issues with the [Eclipse code formatter plugin](https://plugins.jetbrains.com/plugin/6546) in IntelliJ to get this profile working. If you manage to do so, document instructions into the [ImageJ wiki](http://imagej.net/Coding_style).

Alternatively, you could ask for (old) Eclipse XML preference files from @hinerm or @ctrueden, and see if you can get the formatting working from them

**Comment by ctrueden** [comment]
> you could ask for (old) Eclipse XML preference files from @hinerm or @ctrueden, and see if you can get the formatting working from them

It should be a simple matter of:

1. Installing Eclipse
2. Importing the `.epf` file
3. Exporting individual `.xml` files

No need to involve others when you can DIY quickly!

**Comment by rimadoma** [comment]
Figured how to get XML style file from Eclipse working in IntelliJ. Formatting commits will follow.
