### ISSUE TITLE
NoClassDefFoundError when initializing SciView

### ISSUE THREAD

**Issue by rimadoma** [bonej-org/BoneJ2#93]
SciView works when launched from IntelliJ, but when when it's installed into a local copy of Fiji with `mvn -Dimagej.app.directory=/path/ -Ddelete.other.versions=true clean install` then plug-in crashes with
```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: com/jogamp/opengl/math/FloatUtil
	at cleargl.GLMatrix.setIdentity(GLMatrix.java:41)
	at cleargl.GLMatrix.getIdentity(GLMatrix.java:46)
	at graphics.scenery.Node.<init>(Node.kt:73)
	at graphics.scenery.Scene.<init>(Scene.kt:11)
	at graphics.scenery.SceneryBase.<init>(SceneryBase.kt:39)
	at sc.iview.SciView.<init>(SciView.java:48)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:110)
	at org.bonej.wrapperPlugins.SurfaceFractionWrapper.renderSurfaces(SurfaceFractionWrapper.java:201)
	at org.bonej.wrapperPlugins.SurfaceFractionWrapper.run(SurfaceFractionWrapper.java:125)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.math.FloatUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```
when it tries to initialize SciView.

Steps to reproduce
1. `git clone` commit a91a706f251b266174fd19c5f3a57771dd4172c8
2. Build and deploy packages to Fiji `mvn -Dimagej.app.directory=/path/ -Ddelete.other.versions=true clean install`
3. Launch Fiji
4. File > Open Samples > Bat Cochlea Volume
5. Plugins > BoneJ > Fraction > Surface fraction
6. Tick _Render bone mesh_

**Comment by rimadoma** [comment]
Just had a check, and this is not caused by the POM exclusions introduced in #86

**Comment by rimadoma** [comment]
Environment tested:
- Ubuntu Kylin 16.04 LTS 64-bit
- Intel® Xeon(R) CPU E5-2620 v3 @ 2.40GHz × 24
- NVS 310/PCIe/SSE2
- OpenGL rendering
- Latest Fiji

**Comment by ctrueden** [comment]
@rimadoma You cannot install SciView naively using the imagej-maven-plugin, because it has some native JARs that are not put into the correct places. You need to use the [populate-fiji.sh](https://github.com/scenerygraphics/SciView/blob/ea209bb3aa1a70afeaff68d04253f8aae0a97dbd/populate_fiji.sh) script. I do want to improve the imagej-maven-plugin to fix all the edge cases involved, but it is rather far down the totem pole of priorities right now.

**Comment by rimadoma** [comment]
@ctrueden Thanks for the tip! How would this affect installing BoneJ with SciView from the update site? Would a user also have to run the script?

**Comment by ctrueden** [comment]
Nope, the `populate-fiji.sh` script is for people who want deploy the JAR files from the Git working copy. So you as developer use it to create a Fiji.app from which the JARs can be uploaded to the BoneJ update site. See also `sciview_deploy.sh` in the SciView repository, which takes the generated Fiji.app and actually uploads everything to the SciView update site. You could copy and paste these scripts—for now—into the BoneJ repository and use them to keep the BoneJ update site automatically up-to-date. Make sure you tweak them to enable the SciView update site for the generated Fiji.app, so that only the BoneJ-specific files get uploaded to BoneJ.

On the user side, they will then simply enable the SciView and BoneJ update sites, and get everything they need in the right places.

**Comment by rimadoma** [comment]
Is there anything else to using the script than calling
`./populate-fiji.sh`
and then 
`mvn install -Dimagej.app.directory=Fiji.app -Dmaven.test.skip=true `
for my stuff?
Everything installs nicely, but calls to SciView just seem to freeze Fiji. @kephale Have you experienced anything similar?

**Comment by ctrueden** [comment]
Do not call `mvn install -Dimagej.app.directory=Fiji.app -Dmaven.test.skip=true`—the `populate-fiji.sh` already does that on line 66. It should take care of everything. If you invoke the `imagej-maven-plugin` again afterward, it will put back the native libraries into the wrong places, and there will be two copies of things.

> calls to SciView just seem to freeze Fiji.

Does SciView work in a regular Fiji installation on that system with the SciView update site enabled? But freezes in the Fiji.app generated by `populate-fiji.sh`? If yes and yes, then you can do a directory diff between the two folders to see what is different.

**Comment by rimadoma** [comment]
Is the command on line 66 missing a Maven goal on purpose?

SciView works on the system when Fiji is launched from IntelliJ, I'll have to get back to you on what's different between a regular installation and the one created by the script.

**Comment by ctrueden** [comment]
> Is the command on line 66 missing a Maven goal on purpose?

The default goal of anything extending `pom-scijava` is `install`.

> I'll have to get back to you on what's different between a regular installation and the one created by the script.

Sounds good, please ping back when you have more info.

**Comment by rimadoma** [comment]
Okay, several discoveries:
1) SciView from the update site works on regular Fiji installation
2) This is because the [update site](http://sites.imagej.net/SciView/jars/) hosts newer versions of SciView and its dependencies than declared in POM of version 0.0.1, namely:
  - sciview-0.0.2-SNAPSHOT (!)
  - scenery-0.2.3-1
  - see attachment for full list
3) The regular installation stops working, if I run `mvn install` on [`pom-bonej2`](https://github.com/bonej-org/BoneJ2/blob/sciview/Modern/pom.xml), probable culprit is the older version of scenery (see attachment for full list of differences.
4) Same thing probably explains why `populate_fiji.sh` doesn't work

![diff-sciview-update-bonej](https://user-images.githubusercontent.com/14994878/37472341-b9861b8e-2863-11e8-8720-0706859153e3.png)
_Difference between what BoneJ installs from dependency on sciview-0.0.1 v. what's on the update site (Java 8 updates appear because this branch still depends on `pom-scijava 17.1.1`)_

**Comment by rimadoma** [comment]
In the light of this new info I tried hacking my POM with a dependency to the newer `scenery` (with exclusions) and `graphics.scenery:spirvcrossj`, which did lead to a _new_ `NoClassDefFoundError`.

**Comment by rimadoma** [comment]
This problem can solved by using the installation script `populate-fiji.sh`. In addition to running the script, you have to manually copy the following packages to the `Fiji.app/jars/` directory: [populate-fiji-hack.txt](https://github.com/bonej-org/BoneJ2/files/2167351/populate-fiji-hack.txt). You might be able to get around the manual step by adding the necessary (runtime) dependencies to the POM, but I won't investigate this now.

In any case this issue is temporary, because in future the increasing integration between _Fiji_ and _SciView_ should solve these dependency issues, as _SciView_ will work in your _Fiji_ installation out-of-the-box.

**Comment by ctrueden** [comment]
Yeah, I certainly want to smarten up the scijava-maven-plugin's `copy-jars` goal to do the right thing in more cases, and eliminate the need for complicated Fiji populator scripts. SciView also suffers from this issue right now, and eventually we will go through the edge cases and make them work one by one. And then BoneJ2 should reap the benefits as well.
